### ISSUE TITLE
Won't accept calibrations in mmol/L

### ISSUE THREAD

**Issue by thebookins** [xdrip-js/Lookout#36]
The pending message is "Calibrate @ --". For some reason the value in mmol/L isn't being converted before constructing the calibrate message.

**Comment by jpcunningh** [comment]
I'm looking at it now and will let you know when I get it working.

Thanks!

**Comment by jpcunningh** [comment]
@thebookins, the conversion is happening after the field validation happens in cgm/sensor/calibrate.html.  If I change the ng-min to 0, it goes through fine. I saw it work with mmol/L 2 days ago, so I'm not sure what could have changed to move the angular validation to happen before the filter that converts the units vs. after.

Any ideas? I'm looking for options to either control when the filter or validation happens to make them switch order or a way to dynamically change the validation boundaries based on which units are set in the preferences.

**Comment by jpcunningh** [comment]
@thebookins, please checkout PR at https://github.com/xdrip-js/Lookout/pull/37

**Comment by thebookins** [comment]
Yeah, I don't understand either. It used to just work with mmol/L, as the `ng-min` and `ng-max` were applied after conversion to mg/dL. #37 looks good, but it would be nicer if we didn't have to do it that way. Do you think an update to Angular could be to blame?

I'll try to spend a bit of time understanding what order stuff is happening in; if that doesn't clear stuff up, then we'll go with #37?

**Comment by thebookins** [comment]
[This](https://github.com/Narretz/angular.js/commit/74d96b9ccd1d26bc6d2918235e8142e6bbf09e39) might have something to do with it?

**Comment by jpcunningh** [comment]
Good find, @thebookins ! That looks like exactly what is happening.

The Angular commit indicates overwriting the min/max validator vs. changing the validation boundaries like in #37 .

Any preference to which path to take?

**Comment by thebookins** [comment]
I added #38 as an option to resolve this issue (overriding the min/max validators). I think I prefer this option since it's more DRY (and we don't have to insert SharedState into the sensor controller). #37 has some advantages, chief of which is that we can then use `min` and `max` attributes instead of `ng-min` and `ng-max`, which turns on HTML5 validation, which supplies error messages like this:
<img width="414" alt="screen shot 2018-08-06 at 7 45 23 pm" src="https://user-images.githubusercontent.com/12263040/43711667-daaba954-99b6-11e8-9e50-dd83fcc8acea.png">
Do you have a preference @jpcunningh ?

**Comment by jpcunningh** [comment]
I prefer providing the HTML5 validation. I don't think #37 does that, yet. It was giving a highlighted border when validation failed, but not a descriptive message like the screen capture above.

Does it only need a change from ng-min to min and mg-max to max?

I'm a little out of my element. 😄 

Thanks!

**Comment by jpcunningh** [comment]
That sounds like a good plan. I changed ng-min and ng-max to simply min and max and got the coolest little popup validation error box! I'll merge #37, and we'll leave #38 open until we are satisfied with #37 .

Thanks, Paul!

**Comment by jpcunningh** [comment]
@thebookins, any objection to closing this issue and the associated PR #38? Any issues with the way PR #37 handled the validation  issue?

**Comment by jpcunningh** [comment]
Validation added and verified with #37.
